### ISSUE TITLE
npm error Missing script: "build:vscode"

### ISSUE THREAD

**Issue by and-win** [jowharshamshiri/tg-hcl-lsp#1]
Hi,
I'm trying to build the lsp to use in VScode, but got the error:

```bash
~/opt/tg-hcl-lsp main
❯ npm run build:vscode
npm error Missing script: "build:vscode"
npm error
npm error To see a list of scripts, run:
npm error   npm run
npm error A complete log of this run can be found in: /home/andwin/.npm/_logs/2024-11-02T10_58_29_819Z-debug-0.log

~/opt/tg-hcl-lsp main
❯ npm run
Lifecycle scripts included in hcl-lsp@1.0.0:
  postinstall
    cd client && bun install && cd ../server && bun install && cd ..
  test
    sh ./scripts/e2e.sh
available via `npm run-script`:
  vscode:prepublish
    bun run compile
  compile
    tsc -b
  watch
    tsc -b -w
  lint
    eslint ./client/src ./server/src --ext .ts,.tsx
```
Log file:
```
~/opt/tg-hcl-lsp main
❯ bat /home/andwin/.npm/_logs/2024-11-02T10_58_29_819Z-debug-0.log
───────┬────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       │ File: /home/andwin/.npm/_logs/2024-11-02T10_58_29_819Z-debug-0.log
───────┼────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ 0 verbose cli /usr/bin/node /usr/bin/npm
   2   │ 1 info using npm@10.9.0
   3   │ 2 info using node@v18.20.4
   4   │ 3 silly config load:file:/usr/lib/node_modules/npm/npmrc
   5   │ 4 silly config load:file:/home/andwin/opt/tg-hcl-lsp/.npmrc
   6   │ 5 silly config load:file:/home/andwin/.npmrc
   7   │ 6 silly config load:file:/etc/npmrc
   8   │ 7 verbose title npm run build:vscode
   9   │ 8 verbose argv "run" "build:vscode"
  10   │ 9 verbose logfile logs-max:10 dir:/home/andwin/.npm/_logs/2024-11-02T10_58_29_819Z-
  11   │ 10 verbose logfile /home/andwin/.npm/_logs/2024-11-02T10_58_29_819Z-debug-0.log
  12   │ 11 silly logfile start cleaning logs, removing 2 files
  13   │ 12 silly logfile done cleaning log files
  14   │ 13 verbose stack Error: Missing script: "build:vscode"
  15   │ 13 verbose stack
  16   │ 13 verbose stack To see a list of scripts, run:
  17   │ 13 verbose stack   npm run
  18   │ 13 verbose stack     at #run (/usr/lib/node_modules/npm/lib/commands/run-script.js:111:13)
  19   │ 13 verbose stack     at async RunScript.exec (/usr/lib/node_modules/npm/lib/commands/run-script.js:40:7)
  20   │ 13 verbose stack     at async Npm.exec (/usr/lib/node_modules/npm/lib/npm.js:207:9)
  21   │ 13 verbose stack     at async module.exports (/usr/lib/node_modules/npm/lib/cli/entry.js:74:5)
  22   │ 14 error Missing script: "build:vscode"
  23   │ 14 error
  24   │ 14 error To see a list of scripts, run:
  25   │ 14 error   npm run
  26   │ 15 verbose cwd /home/andwin/opt/tg-hcl-lsp
  27   │ 16 verbose os Linux 6.11.5-arch1-1
  28   │ 17 verbose node v18.20.4
  29   │ 18 verbose npm  v10.9.0
  30   │ 19 verbose exit 1
  31   │ 20 verbose code 1
  32   │ 21 error A complete log of this run can be found in: /home/andwin/.npm/_logs/2024-11-02T10_58_29_819Z-debug-0.log
───────┴────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

```

**Comment by rtizzy** [comment]
@and-win 

I believe he changed the name of the command but didn't update the README.md

Pretty certain it's:

`npm run vscode:prepublish`

**Comment by lucalooz** [comment]
Were you able to install and use the extension? 
Probably I'm failing at something very obvious :D

**Comment by jowharshamshiri** [comment]
@lucalooz 

i am working on a new and improved reworked version to be released in a couple of days but for the time being, please refetch the repo and then at root do:

npm install
npm run compile
code .

and then in vscode run the launch configuration and open a terragrunt hcl file. 

happy coding.

**Comment by jowharshamshiri** [comment]
@lucalooz @rtizzy @and-win 
It's now published in vscode marketplace under "Terragrunt Language Server". I also updated the readme with instructions if you want to contribute. :)
